### ISSUE TITLE
Keine Reset Funktion

### ISSUE THREAD

**Issue by jhuebner200505** [TGM-HIT/sew9-2324-worttrainer-pdamianik#1]
Die Daten werden zwar korrekt in die Datei gespeichert und beim öffnen wieder geladen, jedoch ist keine Reset Funktion vorhanden, um das Spiel von neu beginnen zu können.
Dies sollte am besten genauso wie die Einsicht in die Statistik über die Menü Option verfügbar sein.

**Comment by pdamianik** [comment]
Ein Reset-Button ist sehr nützlich und definitiv etwas, was von der aktuellen Version fehlt.
Ich denke, es wäre allerdings besser, wenn die Reset Funktion in dem Fenster der Statistik erreichbar ist, anstatt als seperate Menü Funktion.

**Comment by jhuebner200505** [comment]
das denke ich nicht.

**Comment by pdamianik** [comment]
So, wie ich das verstehe, möchtest Du den Reset Button in diesem Menü haben.

![image](https://github.com/TGM-HIT/sew9-2324-worttrainer-pdamianik/assets/39028343/cd5ae1bb-3309-4e94-948d-beef97804040)

Ich denke aber, dass User den Button eher im Statistik-Fenster suchen würden.

![image](https://github.com/TGM-HIT/sew9-2324-worttrainer-pdamianik/assets/39028343/7b381abf-f84d-4bab-a450-7ebe22de267c)

**Comment by pdamianik** [comment]
Teste bitte den Code der Pr #2
